# Generated by Django 4.1 on 2024-02-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', models.IntegerField()),
                ('make', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('vehicle_class', models.CharField(max_length=50)),
                ('engine_size', models.FloatField()),
                ('cylinders', models.IntegerField()),
                ('transmission', models.CharField(max_length=5)),
                ('fuel_type', models.CharField(max_length=5)),
                ('city', models.FloatField()),
                ('highway', models.FloatField()),
                ('combined', models.FloatField()),
                ('combined_mpg', models.IntegerField()),
                ('CO2_Emission', models.IntegerField()),
                ('CO2_Rating', models.IntegerField()),
                ('smog_rating', models.IntegerField()),
                ('motor', models.IntegerField()),
                ('city_kWh', models.FloatField()),
                ('highway_kWh', models.FloatField()),
                ('combined_kWh', models.FloatField()),
                ('range', models.IntegerField()),
                ('recharge_time', models.IntegerField()),
                ('fuel_type2', models.CharField(max_length=5)),
                ('range2', models.IntegerField()),
                ('combined_PHEV', models.FloatField()),
                ('vehicle_type', models.CharField(choices=[('Conventional', 'Conventional'), ('PHEV', 'PHEV'), ('BEV', 'BEV')], max_length=15)),
            ],
        ),
    ]
